server:
  port: 7031
spring:
  application:
    name: platform-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7030/eureka/
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

url:
  filter:
    permission: /permissions/refresh = ANONYMOUS\n/login = ANONYMOUS\n/** = USER

security:
  oauth2:
#    client:
#      access-token-uri: http://platform-gateway/oauth/token
#      user-authorization-uri: http://platform-gateway/oauth/authorize
#      client-id: webapp
    resource:
      filter-order: 3
#      user-info-uri: http://platform-sys/auth/info
#      prefer-token-info: false